# Claude Usage Tracker Configuration
# This file contains default settings for the usage tracker

# Model pricing (per million tokens)
models:
  claude-3-opus-20240229:
    name: "Claude 3 Opus"
    input: 15.0
    output: 75.0
    cached: 1.875
    
  claude-3-sonnet-20240229:
    name: "Claude 3 Sonnet"
    input: 3.0
    output: 15.0
    cached: 0.375
    
  claude-3.5-sonnet-20241022:
    name: "Claude 3.5 Sonnet"
    input: 3.0
    output: 15.0
    cached: 0.375
    
  claude-3-haiku-20240307:
    name: "Claude 3 Haiku"
    input: 0.25
    output: 1.25
    cached: 0.03125
    
  claude-3.5-haiku-20241022:
    name: "Claude 3.5 Haiku"  
    input: 0.8
    output: 4.0
    cached: 0.1
    
  claude-sonnet-4-20250514:
    name: "Claude Sonnet 4"
    input: 3.0
    output: 15.0
    cached: 0.375
    
  claude-opus-4-20250514:
    name: "Claude Opus 4"
    input: 15.0
    output: 75.0
    cached: 1.875

# Rate limits by plan type
rate_limits:
  Pro:
    price: 20
    weekly:
      sonnet4:
        min: 40
        max: 80
      opus4:
        min: 4
        max: 8
        
  "$100 Max":
    price: 100
    weekly:
      sonnet4:
        min: 140
        max: 280
      opus4:
        min: 15
        max: 35
        
  "$200 Max":
    price: 200
    weekly:
      sonnet4:
        min: 240
        max: 480
      opus4:
        min: 24
        max: 40

# Token usage estimates (per hour of active work)
token_estimates:
  sonnet4:
    min: 50000
    max: 100000
  opus4:
    min: 40000
    max: 80000

# Batch API pricing (50% discount)
batch_api_discount: 0.5

# Data source paths
data_paths:
  - "~/.config/claude/projects"
  - "~/.claude/projects"
  
# Model recommendation mappings
recommendations:
  code_generation:
    model: "claude-3.5-sonnet-20241022"
    confidence: 0.8
  debugging:
    model: "claude-opus-4-20250514"
    confidence: 0.7
  code_review:
    model: "claude-3.5-sonnet-20241022"
    confidence: 0.75
  documentation:
    model: "claude-3.5-sonnet-20241022"
    confidence: 0.9
  architecture:
    model: "claude-opus-4-20250514"
    confidence: 0.8
  complex_analysis:
    model: "claude-opus-4-20250514"
    confidence: 0.9
  simple_query:
    model: "claude-3.5-sonnet-20241022"
    confidence: 0.95
  refactoring:
    model: "claude-3.5-sonnet-20241022"
    confidence: 0.8
